apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ror-mongodb-backup.fullname" . }}
  labels:
    {{- include "ror-mongodb-backup.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.backup.storage.storageClassName }}
  storageClassName: {{ .Values.backup.storage.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.backup.storage.size }}
