# golangci-lint configuration
run:
  timeout: 5m
  tests: true
  skip-dirs:
    - tmp
    - dist
    - vendor
    - testdata
    - charts

linters:
  enable:
    - bodyclose
    - dupl
    - errcheck
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused

linters-settings:
  govet:
    shadow: true
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  lll:
    line-length: 140

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - dupl
        - gosec
  max-issues-per-linter: 0
  max-same-issues: 0
