FROM golang:1.26-alpine AS builder
RUN apk add --no-cache git
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go mod tidy && CGO_ENABLED=0 go build -o /bin/ror-api ./cmd/api

FROM gcr.io/distroless/static:nonroot
WORKDIR /
COPY --from=builder /bin/ror-api /bin/ror-api
EXPOSE 8080
ENTRYPOINT ["/bin/ror-api"]
