enabled: true

status:
  namespace: nhn-ror
  port: "8080"
  logLevel: "info"
  prometheusUrl: "http://prometheus-kube-prometheus-prometheus.prometheus-operator.svc:9090"

replicaCount: 1

image:
  repository: ghcr.io/norskhelsenett/ror-statuspage
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  runAsNonRoot: true
  fsGroup: 2000
  runAsUser: 1001
  runAsGroup: 1001

securityContext:
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  seccompProfile:
    type: RuntimeDefault
  capabilities:
    drop:
      - ALL

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: avi-ingress-class-helsenett
  host: status.ror.nhn.no
  path: /
  pathType: Prefix

resources:
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi

nodeSelector: {}
tolerations: []
affinity: {}
