apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ror-statuspage.fullname" . }}-config
  labels:
    {{- include "ror-statuspage.labels" . | nindent 4 }}
data:
  STATUS_NAMESPACE: {{ .Values.status.namespace | quote }}
  STATUS_PORT: {{ .Values.status.port | quote }}
  PROMETHEUS_URL: {{ .Values.status.prometheusUrl | quote }}
