apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "ror-api.fullname" . }}-publisering
  namespace: nhn-ror
  annotations:
    gatewayapi-operator.vitistack.io/enabled: "true"
    ipam.vitistack.io/zone: hnet-private # eller hnet-public eller inet
    gatewayapi-operator.vitistack.io/cluster-issuer: internpki # eller letsencrypt-prod
spec:
  parentRefs:
    - name: ror-gateway 
      sectionName: {{ .Values.api.fqdn}}
      namespace: gateways
  hostnames:
    - {{ .Values.api.fqdn}}
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: {{ include "ror-api.fullname" . }}
          port: {{ .Values.service.port }}
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: {{ .Values.ingress.path }}
